### PR TITLE
revised to add stream capability to this module for RDO-2124

### PR DESCRIPTION
**Pull request by kyrian-hmcts**
Fill these in where possible for each PR:

### CODE REVIEW

**Review by Tiki-God — COMMENTED** [review]
Is there anything preventing a HTTP listener and stream listener both listening on the same port?

More importantly does that cause issues for Nginx.  I seem to remember it not liking it too much

**Comment by kyrian-hmcts** [comment]
Jon, not sure on the direction/causality of your question, but... If we try to put both TCP and HTTP stuff on the same host/port combination it will choke and stop nginx starting up due to unable to bind errors etc. For now this PR is to cover the immediate issue for Janis on RDO-2124. I have captured the need for safeguards as a follow-up issue in RDO-2149, to be done as soon as possible afterwards.

**Comment by kyrian-hmcts** [comment]
PS. There is quite some urgency for this from Janis' perspective, hence I've stepped in on this to build the PR/code up.

**Review by Tiki-God — APPROVED** [review]
Fine for me as long as the follow up work is tracked :)

**Pull request merged**
